### ISSUE TITLE
[Search result- filter] rating sort as high-to-low in search result 

### ISSUE THREAD

**Issue by heesun-task** [rizgif/2800-202310-BBY09#17]
**Description**
If I sort "High-to-low"
N/A comes first.  (e.g.   N/A - 5 - 4 - 3 - ...)

<img width="425" alt="image" src="https://github.com/rizgif/2800-202310-BBY09/assets/65277541/df146577-3d23-43b9-b809-f2a88ec77ca5">

**Comment by heesun-task** [comment]
@rizgif could you plz check this?

**Comment by rizgif** [comment]
Bug Fixed. 

<img width="975" alt="image" src="https://github.com/rizgif/2800-202310-BBY09/assets/88169090/9c6aec14-0fd6-42e5-a1be-133c280f79bb">
