### ISSUE TITLE
if there is no key word entered in the search bar, there is a error (in cyclic app)

### ISSUE THREAD

**Issue by chelseaY119** [rizgif/2800-202310-BBY09#21]
<img width="713" alt="Screenshot 2023-05-23 at 10 22 51" src="https://github.com/rizgif/2800-202310-BBY09/assets/122335568/5ccf284d-fa85-4d28-9173-8ec2018d3443">

**Comment by rizgif** [comment]
Fixed.

**Comment by heesun-task** [comment]
@chelseaY119

**Comment by chelseaY119** [comment]
if the user is logged in, the same error happened again
